### ISSUE TITLE
now and currentTimestamp function must be declared to be stateful 

### ISSUE THREAD

**Issue by kanduibm** [IBMStreams/streamsx.datetime#11]
Building main composite: application::DateTimeTest using build configuration: BuildConfig
/home/kandu/InfoSphere_Streams_fvt_4.2/4.2.0.0/bin/sc -M application::DateTimeTest --output-directory=output/application.DateTimeTest/BuildConfig --data-directory=data -a -t /home/kandu/git/streamsx.datetime/com.ibm.streamsx.datetime: --no-toolkit-indexing --no-mixed-mode-preprocessing
/home/kandu/git/streamsx.datetime/com.ibm.streamsx.datetime/com.ibm.streamsx.datetime/functions.spl:19:33: CDISP0466E ERROR: The now function must be declared to be stateful because it calls the getTimestamp function, which is stateful.
/home/kandu/git/streamsx.datetime/com.ibm.streamsx.datetime/com.ibm.streamsx.datetime/functions.spl:25:46: CDISP0466E ERROR: The currentTimestamp function must be declared to be stateful because it calls the getTimestamp function, which is stateful.

I have initialized the pull request for this simple fix. Please review 

Thanks

**Comment by ddebrunner** [comment]
Fixed by pull request #10
