### ISSUE TITLE
Function proposal: parseDateTime

### ISSUE THREAD

**Issue by leongor** [IBMStreams/streamsx.datetime#13]
Recently we've developed `parseDateTime` function for Streams Designer. Here 2 main reasons behind it:
1. `fromIso8601ToTimestamp` function from `com.ibm.streamsx.datetime` toolkit is very strict, while customers frequently use timestamps without time zones or nanseconds.
2. A single tuple can easily have multiple timestamps to parse, so performance is crucial. `parseDateTime` is built over [Boost.Spirit](https://theboostcpplibraries.com/boost.spirit), one of the blazing fast C++ parsers.

**Comment by ddebrunner** [comment]
Does this mean the toolkit will become platform dependent?

**Comment by leongor** [comment]
No, it depends on streams_boost header only libraries.

**Comment by ddebrunner** [comment]
Can you expand more on "without nanoseconds"?

Doesn't the existing `fromIso8601ToTimestamp` support times without nanoseconds?

**Comment by ddebrunner** [comment]
Ok - I'm getting it, as documented `fromIso8601ToTimestamp` does say a **full** ISO8601 time.

So looks like this function is needed, for two reasons:
  - support partial ISO8601 timestamps.
  - performance
 
The issue I'm struggling with is what exact formats does it support, these need to be documented in its SPLDOC, so an app developer can understand what formats they can use. E.g. if implemented would it deprecate `fromIso8601ToTimestamp` as it would support a superset of that functionality?

 Then if it's supporting non-ISO8601 formats, what are they and are they standard, e.g. just allowing any separator runs the risk of Streams potentially producing timestamps no-one else can use. Standards are there for a reason.
