### ISSUE TITLE
contribute some functions -- moved from toolkits to here

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/streamsx.datetime#5]
How can I contribute to add functions such as :

/**
* Convert a timestamp into an string ISO format
* use 'man strptime' to get the list of available format
*/

public rstring timestampToISO(timestamp dtime)
{
mutable Sys.tm timetuple = { } ;
time(dtime, timetuple) ;
/*
* %Y The year, including century (for example, 1991).
* %m The month number (1-12).
* %d or %e The day of month (1-31).
*/
rstring dateString = strftime(timetuple, "%Y-%m-%d") ;

/*
* %T        Equivalent to %H:%M:%S
*/
rstring timeString = strftime(timetuple, "%T") ;
/*
 *  %z     An RFC-822/ISO 8601 standard timezone specification.
 */
rstring timeZoneString = strftime(timetuple, "%z") ;

float64 milliseconds =(float64) getNanoseconds(dtime) / 1000000f ;
return dateString + "T" + timeString + "." +(rstring)((uint32) milliseconds) + timeZoneString ;

}

**Comment by ddebrunner** [comment]
Sorry missed this, but how to contribute is described here:

https://github.com/IBMStreams/administration/wiki/Contributing-to-IBMStreams#id-like-to-contribute-to-an-existing-toolkit

Basically for the repository, make your changes, and submit a pull request. I'd recommend using a branch in your repo.

**Comment by ddebrunner** [comment]
Pull request #7 added some ISO conversions.
